version: '3'

services:

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - pgdb
    entrypoint: liquibase
    environment:
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog.xml
    command: --url=jdbc:postgresql://pgdb/${POSTGRES_DB} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=changelog.xml update
    volumes:
      - ./scripts:/liquibase/scripts
      - ./changelog.xml:/liquibase/changelog.xml
    networks:
      - lbnet

  pgdb:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: root
    ports:
      - "5432:5432"
    networks:
      - lbnet

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8080:80"
    networks:
      - lbnet
    depends_on:
      - pgdb

networks:
  lbnet:
